drop table ABSENSI_PEGAWAI cascade constraints purge;
drop table ABSENSI_PENGUNJUNG cascade constraints purge;
drop table BUKU cascade constraints purge;
drop table BUKU_PENGARANG cascade constraints purge;
drop table D_BOOKING cascade constraints purge;
drop table D_DENDA cascade constraints purge;
drop table D_PINJAM cascade constraints purge;
drop table H_BOOKING cascade constraints purge;
drop table DENDA cascade constraints purge;
drop table H_PINJAM cascade constraints purge;
drop table KATEGORI cascade constraints purge;
drop table MEMBER cascade constraints purge;
drop table PEGAWAI cascade constraints purge;
drop table PENERBIT cascade constraints purge;
drop table PENGARANG cascade constraints purge;
drop table POIN cascade constraints purge;

CREATE TABLE MEMBER
(
	ID_MEMBER VARCHAR2(6) CONSTRAINT PK_ID_MEMBER PRIMARY KEY,
	NAMA_MEMBER VARCHAR2(20) NOT NULL,
	FOTO_MEMBER BLOB,
	ALAMAT_MEMBER VARCHAR2(30) NOT NULL,
	TELP_MEMBER VARCHAR2(12) NOT NULL,
	TTL_MEMBER DATE NOT NULL,
	JENIS_MEMBER VARCHAR2(5) CHECK(JENIS_MEMBER='SISWA' OR JENIS_MEMBER='GURU'),
	JK_MEMBER VARCHAR2(1) CHECK(JK_MEMBER='P' OR JK_MEMBER='L'),
	PASSWORD_MEMBER VARCHAR2(10) NOT NULL,
    STATUS_AKTIF VARCHAR2(1) CHECK(STATUS_AKTIF='0' OR STATUS_AKTIF='1'),
	TGL_EXP DATE NOT NULL
);

CREATE TABLE ABSENSI_PENGUNJUNG
(
	NOMOR_ABSENSI_PENGUNJUNG VARCHAR2(12) CONSTRAINT PK_NOMOR_ABSENSI_PENGUNJUNG PRIMARY KEY,
	NAMA_PENGUNJUNG VARCHAR2(20) NOT NULL,
	WAKTU_DATANG_ABSEN DATE NOT NULL
);

CREATE TABLE PEGAWAI
(
	ID_PEGAWAI VARCHAR2(6) CONSTRAINT PK_ID_PEGAWAI PRIMARY KEY,
	NAMA_PEGAWAI VARCHAR2(20) NOT NULL,
	FOTO_PEGAWAI BLOB,
	ALAMAT_PEGAWAI VARCHAR2(30) NOT NULL,
	TELP_PEGAWAI VARCHAR2(12) NOT NULL,
	TTL_PEGAWAI DATE NOT NULL,
	JK_PEGAWAI VARCHAR2(1) CHECK(JK_PEGAWAI='P' OR JK_PEGAWAI='L'),
	PASSWORD_PEGAWAI VARCHAR2(10) NOT NULL,
    STATUS_AKTIF VARCHAR2(1) CHECK(STATUS_AKTIF='0' OR STATUS_AKTIF='1')
);

CREATE TABLE ABSENSI_PEGAWAI
(
	ID_ABSEN NUMBER(4) CONSTRAINT PK_ID_ABSEN PRIMARY KEY,
	ID_PEGAWAI VARCHAR2(6) REFERENCES PEGAWAI(ID_PEGAWAI),
    WAKTU_DATANG_ABSEN DATE NOT NULL,
	WAKTU_PULANG_ABSEN DATE
);

CREATE TABLE PENERBIT
(
	ID_PENERBIT VARCHAR2(7) CONSTRAINT PK_ID_PENERBIT PRIMARY KEY,
	NAMA_PENERBIT VARCHAR2(30) NOT NULL,
	ALAMAT_PENERBIT VARCHAR2(100) NOT NULL,
	KOTA_PENERBIT VARCHAR2(20) NOT NULL,
	TELP_PENERBIT VARCHAR2(12) NOT NULL
);

CREATE TABLE KATEGORI
(
    ID_KATEGORI VARCHAR2(5) CONSTRAINT PK_ID_KATEGORI PRIMARY KEY,
    NAMA_KATEGORI VARCHAR2(50) NOT NULL
);

CREATE TABLE BUKU
(
	ID_BUKU VARCHAR2(5) CONSTRAINT PK_ID_BUKU PRIMARY KEY,
	ID_PENERBIT VARCHAR2(7) REFERENCES PENERBIT(ID_PENERBIT),
	JUDUL_BUKU VARCHAR2(100) NOT NULL,
	COVER_BUKU BLOB,
	TAHUN_TERBIT DATE NOT NULL,
	ID_KATEGORI VARCHAR2(11) REFERENCES KATEGORI(ID_KATEGORI),
	DIBOOKING VARCHAR2(1) NOT NULL CHECK(DIBOOKING='1' OR DIBOOKING='0'),
	DIPINJAM VARCHAR2(1) NOT NULL CHECK(DIPINJAM='1' OR DIPINJAM='0'),
    BAWA_PULANG VARCHAR2(1) NOT NULL CHECK(BAWA_PULANG='1' OR BAWA_PULANG='0'),
    STATUS_BUKU VARCHAR2(1) CHECK(STATUS_BUKU='0' OR STATUS_BUKU='1')
);

CREATE TABLE PENGARANG
(
	ID_PENGARANG VARCHAR2(6) CONSTRAINT PK_ID_PENGARANG PRIMARY KEY,
	NAMA_PENGARANG VARCHAR2(50) NOT NULL
);

CREATE TABLE BUKU_PENGARANG
(
	ID_BUKU VARCHAR2(5) REFERENCES BUKU(ID_BUKU),
	ID_PENGARANG VARCHAR2(6) REFERENCES PENGARANG(ID_PENGARANG)
);

CREATE TABLE H_BOOKING
(
	ID_BOOKING VARCHAR2(12) CONSTRAINT PK_ID_BOOKING PRIMARY KEY,
	ID_MEMBER VARCHAR2(6) REFERENCES MEMBER(ID_MEMBER),
	TGL_BOOKING DATE NOT NULL,
	JUMLAH_BOOKING NUMBER(5) NOT NULL,
    STATUS_BOOKING VARCHAR2(1) CHECK(STATUS_BOOKING='0' OR STATUS_BOOKING='1')
);

CREATE TABLE D_BOOKING
(
	ID_BOOKING VARCHAR2(12) REFERENCES H_BOOKING(ID_BOOKING),
	ID_BUKU VARCHAR2(5) REFERENCES BUKU(ID_BUKU)
);

CREATE TABLE H_PINJAM
(
	NOMOR_PINJAM VARCHAR2(12) CONSTRAINT PK_NOMOR_PINJAM PRIMARY KEY,
	ID_MEMBER VARCHAR2(6) REFERENCES MEMBER(ID_MEMBER),
	TGL_PINJAM DATE NOT NULL,
	TGL_BATAS_PINJAM DATE NOT NULL,
	TGL_KEMBALI DATE,
	JUMLAH_BUKU NUMBER(5) NOT NULL,
    STATUS_PINJAM VARCHAR2(1) CHECK(STATUS_PINJAM='0' OR STATUS_PINJAM='1')
);

CREATE TABLE D_PINJAM
(
	NOMOR_PINJAM VARCHAR2(11) REFERENCES H_PINJAM(NOMOR_PINJAM),
	ID_BUKU VARCHAR2(5) REFERENCES BUKU(ID_BUKU)
);

CREATE TABLE POIN
(
	NOMOR_PINJAM VARCHAR2(11) REFERENCES H_PINJAM(NOMOR_PINJAM),
	ID_MEMBER VARCHAR2(6) REFERENCES MEMBER(ID_MEMBER),
	JUMLAH_POIN NUMBER(5)
);

CREATE TABLE DENDA
(
	NOMOR_DENDA VARCHAR2(5) CONSTRAINT PK_NOMOR_DENDA PRIMARY KEY,
	JENIS_DENDA VARCHAR2(20) NOT NULL,
	HARGA_DENDA NUMBER(10) NOT NULL
);

CREATE TABLE D_DENDA
(
	NOMOR_PINJAM VARCHAR2(11) REFERENCES H_PINJAM(NOMOR_PINJAM),
	NOMOR_DENDA VARCHAR2(8) REFERENCES DENDA(NOMOR_DENDA),
	KETERANGAN VARCHAR2(50)
);

INSERT INTO PEGAWAI(ID_PEGAWAI,NAMA_PEGAWAI,FOTO_PEGAWAI,ALAMAT_PEGAWAI,TELP_PEGAWAI,TTL_PEGAWAI,JK_PEGAWAI,PASSWORD_PEGAWAI,STATUS_AKTIF) VALUES ('admin','ADMIN','','ADMIN','ADMIN',TO_DATE('01/01/01','DD-MM-YYYY'),'L','admin',1);